apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-images
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gerardbulky/jenkins-server-repo.git
    targetRevision: HEAD
    path: ./  # Update this to the correct path if needed
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # Ensure this is the namespace where you want to deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true