apiVersion: v1
kind: Service
metadata:
  name: vault-images
  labels:
    app: vault-images
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: vault-images
  type: LoadBalancer